engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  Checkstyle:
    enabled: true
  Markdown:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
  stylelint:
    enabled: true
    channel: "beta"
  duplication:
    enabled: true
    config:
       languages:
          - javascript
ratings:
   paths:
   - "**.css"
   - "**.java"
   - "**.js"
   - "**.md"
   - "**.less"
   - "**.scss"
   - "**.sss"
exclude_paths:
- lib/**/*
