language: java
jdk: oraclejdk9
sudo: required 
dist: trusty

git:
  depth: 42000

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    - bundler
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
addons:
  coverity_scan:
    project:
      name: "fujaba/NetworkParser"
      description: "Build submitted via Travis CI"
    notification_email: Stefan@uni-kassel.de
    build_command_prepend: "gradle clean"
    build_command:   "gradle -xTest -xJavadoc"
    branch_pattern: master
  #srcclr: true
  sonarcloud:
    organization: "Fujaba"
    branches:
      - master
before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  - unzip -P $SIGNITURE_PASSWORD signiture.zip
before_install:
  - chmod +x gradlew
# safelist
branches:
  only:
  - master
  - develop
after_success: 
  - ./gradlew version build uploadArchives jacocoTestReport coveralls
  # other script steps might be done before running the actual sonarcloud analysis
  - sonar-scanner
after_failure:
  - cat build/reports/tests/test/index.html
  - cat build/reports/tests/test/classes/Gradle*.html
notifications:
  email:
    - Stefan@uni-kassel.de
  # on_success: change
  # on_failure: always
