language: java
jdk: oraclejdk8
sudo: required 
dist: trusty

git:
  depth: 42000
addons:
  coverity_scan:
    project:
      name: "fujaba/NetworkParser"
      description: "Build submitted via Travis CI"
    notification_email: Stefan.Lindel@cs.uni-kassel.de
    build_command_prepend: "gradle clean"
    build_command:   "gradle -xTest -xJavadoc"
    branch_pattern: master
    srcclr: true
before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  - unzip -P $SIGNITURE_PASSWORD signiture.zip
before_install: chmod +x gradlew
# safelist
branches:
  only:
  - master
  - develop
  
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner

  
after_success: ./gradlew version build uploadArchives jacocoTestReport coveralls