package de.uniks.networkparser.gui;

public enum EventTypes {
	CLICK, DOUBLECLICK, CHANGE,
	MOUSEUP, MOUSEDOWN, MOUSEENTER, MOUSELEAVE, MOUSEMOVE,
	KEYPRESS, KEYDOWN, KEYUP,
	RESIZE,
	DRAGSTART, DRAGOVER, DROP, WINDOWEVENT;
}
