package de.uniks.jism.date;

public enum DateField {
	MILLISECOND, MILLISECONDS, MILLISECONDSREAL, MILLISECOND_OF_DAY, MILLISECOND_OF_YEAR,
	SECOND_OF_MINUTE, MINUTE_OF_HOUR, HOUR_OF_DAY, AMPM, TIMEZONE, 
	DAY_OF_WEEK, DAY_OF_MONTH, DAY_OF_YEAR, WEEK_OF_MONTH, WEEK_OF_YEAR,  
	MONTH, YEAR;
}
